In [1]:
import numpy as np

Задание 1

В переменной shape указан размер массива, а в переменной filler указано некоторое (не обязательно числовое) значение.
В одну строку кода создайте массив numpy.array размера shape, состоящего из значений filler.
Массив поместите в переменную data.

In [2]:
shape = (2, 8, 4)
filler = 19

In [3]:
data = np.full(shape, filler)
print(data)


[[[19 19 19 19]
  [19 19 19 19]
  [19 19 19 19]
  [19 19 19 19]
  [19 19 19 19]
  [19 19 19 19]
  [19 19 19 19]
  [19 19 19 19]]

 [[19 19 19 19]
  [19 19 19 19]
  [19 19 19 19]
  [19 19 19 19]
  [19 19 19 19]
  [19 19 19 19]
  [19 19 19 19]
  [19 19 19 19]]]


Задание 2

Буратино закопал золотые монеты на Поле Чудес, и решил отметить закопанные места в переменной field типа numpy.array.
К несчастью, будучи самому себе Буратино, он записал места в одномерном массиве.
Преобразуйте этот массив в массив истинности my_map для Поля (двухмерную карту), если вы знаете,
что на Поле Чудес a грядок (рядов).

In [4]:
np.random.seed(777)
field = np.random.randint(0, 2, size=(42,))
a = 7

In [10]:
my_map = field.reshape(-1, a)
print(my_map)

[[1 1 1 0 1 1 1]
 [1 1 0 1 1 0 0]
 [0 1 0 1 0 0 1]
 [1 0 0 1 1 1 1]
 [1 1 0 0 0 0 1]
 [1 0 0 0 0 0 0]]


Задание 3

Васе необходимо произвести матричное умножение двумерных NumPy-массивов a и b.
К несчастью, Вася случайно изменил размер массива b так, что он не обладает корректными размерами (и, возможно, размерностью) для выполнения умножения.
Измените размер (shape) массива b и выполните матричное умножение за Васю; результат выведите на экран.

In [11]:
np.random.seed(777)
a = np.random.randint(-10, 10, (13, 28))
b = np.random.randint(-5, 5, 224)

In [23]:
result = (a.dot(b.reshape(a.shape[1], -1)))
print(result)

[[  77  125   53  -11  -72   59  240  120]
 [ 113   81   32 -221  -58   99    6    2]
 [  44   40  114  -80   16  -47 -111  192]
 [ -47   97    1   43   37  157   37    2]
 [-158   44   37  113   65  116 -109  -74]
 [ -64  125  148  -42 -144  -62  -29  126]
 [  79   94  -27   89 -145  185    1 -133]
 [-136 -106  -78  -35   14   76  -86 -193]
 [  89   36   29  109   61  -20  -90    4]
 [ -65   19  -13  -16   96  244   12  -95]
 [-143  100  -33  109   66  110   65   25]
 [ -17   41  -73   63  179  233  104 -228]
 [ 144  -28  -56   47   96  -52  147  -86]]


Задание 4
В вашем распоряжении массив A - двумерный numpy.array со абсолютными значениями некоторого набора параметров.
По колонкам записаны отдельные параметры.
Ваша задача - для каждого из параметров произвести стандартизацию.


In [24]:
np.random.seed(777)
A = np.random.randint(1, 180, (100, 15))

In [46]:
def std_f(x):
    std = (x - np.mean(x)) / np.std(x)
    return std

std_arr = np.apply_along_axis(std_f, 0, A)
print(std_arr)

[[ 0.19745051 -0.67262568 -0.69823376 ... -1.20945313 -0.91987258
   1.07684792]
 [ 0.95610768  1.16832619 -1.25336661 ... -0.2925061  -0.05035135
  -0.84074437]
 [-0.62110064  0.52883765 -0.51318948 ...  0.73447457 -1.38496533
   0.13802669]
 ...
 [-0.82074727  0.29629636  0.7821205  ... -1.22779207 -0.45477983
  -1.02051865]
 [ 0.91617835 -0.3044353  -1.13000376 ... -1.39284254  0.09119862
  -1.20029292]
 [-0.68099463 -0.47884127  1.00828574 ... -1.20945313  0.21252717
  -0.76084469]]


Задание 5
Вам даны два массива: массив X со значениями (0, 1) и массив Y со значениями статистики χ2df=2.
Найдите правостороннее критическое значение статистики для α=0.05.

Выведите набор 0 и 1, соответствующих значениям статистики, попавшим в критическую область.
С помощью фильтра замените значения в массиве X по этим позициям на 2.

In [47]:
np.random.seed(777)
X = np.random.randint(0, 1, size=(300, 1))
Y = np.random.chisquare(df=2, size=(300, 1))

In [51]:
print(Y[Y > 0.05])

[ 0.33131531  0.72009442  0.1280883   1.23185509  3.6066933   5.23451079
  2.59648627  2.92631817  0.62724477  2.06581367  0.19604889  0.16608048
  1.781313    0.84117944  8.9973274   1.96953108  2.2900201   1.60707091
  0.6263008   0.93444504  0.50444479  0.41267759  0.99071867  0.42926575
  1.88789399  4.28789096  1.94751569  0.58369867  0.3967319   3.39004029
  0.51074375  1.45488579  1.46168073  1.83445702  1.52122736  1.48508356
  4.52451295  2.93849381  0.26215839  0.70159221  1.89362143  2.59026279
  1.24536801  2.93163093  0.42547336  1.63228782  1.60047686  1.27817231
  3.13932856  0.24489959  2.28703458  0.89988007  0.84382595  1.19392477
  0.05462371  1.07313385  5.10804286  0.19127272  0.75702847  1.50164684
  0.7951785   1.19173441  0.20412504  2.35913655  3.61508769  1.10441357
  3.77796376  1.58280471  0.87423188  2.59839698  0.19710455  4.4672153
  0.81972437  4.44815197  0.70436723  0.71806484  3.28227628  3.63550846
  2.0117818   0.74597833  0.05978179  1.02090911  1.

Задание 6
В университете Вова плохо учил статистику и покупает лотерейные билеты.
Несмотря на это, Вова хорошо знает программирование, поэтому он записал все купленные им билеты в массив numpy.array lottery.
В этом массиве в строках перечислены числа в билете (их всегда одинаковое количество).
Выведите на экран все билеты, в которых отмечено несчастливое для Вовы число 13. Выводить следует по одному билету в одной строке.

In [52]:
np.random.seed(777)
lottery = np.random.choice(90, size=(50, 30))

In [58]:
res = np.where(lottery == 13)
print(lottery[np.unique(res[0])])


[[47 59 38 87 49 71 29 39 89 46 24 39 18 13 14 32 65 82 84 69  7 65 31 59
  74 82 50 62 71 68]
 [88 55 13 43 24 80 84 88 69  1 68 69 75 87 14 79 82 75 31 71 37 68 42 74
  13  7 28 52 81 73]
 [43  9 15  4  2 15 74 66 32 87 16 22 67 65 27 63 55 30 76  2 20 14 13 30
  70 21 16 82 53 36]
 [49 53 62 81 51 50 54 20  7 27 64 22 36 13 24 33 62 13 31 64 11 24 83 31
  64 68 41 71 20 85]
 [78 78 44 35  4  6 77 46 73 32 16 40 37 30 46 89 31 13 89 71 18 63 67 60
  52 76 53 52 35 59]
 [ 4 30 87 83 74 28 31 18 69 63 43 88 71 64 60 10  4  2 76 29 68 23  9 60
  41  4 54 20 13  1]
 [74 71 15 33  3 23 75 42 38 65  4 75 12 13 66 54 32 39 37 73 20 64 73 84
  29  3 73 78 21 38]
 [ 3 27 61 30 83 67  7 14 81 17 68 89 32  1 65 75 54  4 17 38 13 40 30 25
  54 10  9 70 24 38]
 [76 12 88  7 48 33 29 30  5 16 25 11 21 41 15 77 53 79 81 40 43 85 64 13
  71 11 36 27 85 31]
 [66 49 23 42 18 54 18 25 40 41  8 75 68  5 42  3 39 11 43 43 74 23 50 56
  37 43 19 27 86 13]
 [85 70 42 65 77 88 51  8 13 41 18 25 43 17 60 80 